{% set name = "sequence-model" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sequence-dev/sequence/archive/v{{ version }}.tar.gz
  sha256: d3253ed13a826597cabe82690c373be56450fa86ec0c48fb15c9ed3ac8330b20

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - sequence=sequence.cli:sequence


requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - rich-click
    - compaction
    - landlab >=2
    - matplotlib-base
    - netcdf4
    - numpy
    - pyyaml
    - scipy
    - tomlkit
    - tqdm
    - xarray

test:
  imports:
    - sequence

about:
  home: http://github.com/sequence-dev/sequence
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: 'Build stratigraphic sequences'

  # The remaining entries in this section are optional, but recommended.
  description: |
    Sequence is a modular 2D (i.e., profile) sequence stratigraphic
    model that is written in Python and implemented within the
    Landlab framework. Sequence represents time-averaged fluvial
    and marine sediment transport via differential equations. The
    modular code includes components to deal with sea level changes,
    sediment compaction, local or flexural isostasy, and tectonic
    subsidence and uplift.
  doc_url: http://sequence.readthedocs.io/
  dev_url: http://github.com/sequence-dev/sequence

extra:
  recipe-maintainers:
    - mcflugen
